"""ADAPT-X data contracts.

All public models are re-exported here so consumers import from a single
module: ``from adaptx.models import PointCloudFrame``.
"""

from adaptx.models.common import (
    SCHEMA_VERSION,
    AdaptXModel,
    BoundingBox3D,
    CoordinateFrame,
    DataSource,
    Dimensions,
    ObjectClass,
    TimestampedModel,
    Vector3,
    utc_now,
)
from adaptx.models.detection import (
    ClusterRejection,
    DetectionConfiguration,
    DetectionResult,
    RejectedCluster,
)
from adaptx.models.map import (
    AdaptiveMap,
    AdaptiveMapCell,
    OccupancyState,
    ResolutionContext,
    ResolutionLevel,
)
from adaptx.models.objects import DetectedObject
from adaptx.models.point_cloud import (
    XYZ_FIELDS,
    XYZI_FIELDS,
    BasePointCloudFrame,
    PointCloudBounds,
    PointCloudFrame,
    PointCloudSummary,
    RawPointCloudFrame,
)
from adaptx.models.prediction import (
    PRODUCED_STATUSES,
    PredictedTrajectory,
    PredictionStatus,
    TrajectoryPoint,
)
from adaptx.models.prediction_result import (
    PredictionConfiguration,
    PredictionResult,
    SkippedTrack,
)
from adaptx.models.processing import (
    PipelineConfiguration,
    PointCloudProcessingResult,
    ProcessingMetrics,
    ProcessingStage,
    StageMetrics,
)
from adaptx.models.resolution import (
    FIXED_BASELINE_REASON,
    ResolutionDecision,
    ResolutionSource,
)
from adaptx.models.risk import (
    SCORED_RISK_LEVELS,
    ObjectRisk,
    RiskCell,
    RiskFactors,
    RiskField,
    RiskLevel,
)
from adaptx.models.risk_assessment import (
    AssessmentStatus,
    MapContext,
    MapObservation,
    RiskAssessment,
    RiskAssessmentResult,
    RiskConfiguration,
    RiskFactorName,
    TrajectoryRelevance,
    UncertaintyBreakdown,
    UncertaintyReason,
)
from adaptx.models.spatial_map import (
    DEFAULT_MAX_PROJECTED_CELLS,
    MapAccounting,
    MapBounds,
    MappingConfiguration,
    SpatialMap,
    SpatialMapCellField,
    SpatialMapSummary,
)
from adaptx.models.system import (
    CarlaConnectionStatus,
    CarlaStatus,
    ComponentReadiness,
    ComponentStatus,
    ImplementationStatus,
    LiDARSourceStatus,
    LiDARStatus,
    SystemMetrics,
    SystemState,
    SystemStatus,
)
from adaptx.models.tracking import TrackedObject, TrackStatus
from adaptx.models.tracking_result import TrackingConfiguration, TrackingResult
from adaptx.models.vehicle import VehicleState

__all__ = [
    "DEFAULT_MAX_PROJECTED_CELLS",
    "FIXED_BASELINE_REASON",
    "PRODUCED_STATUSES",
    "SCHEMA_VERSION",
    "SCORED_RISK_LEVELS",
    "XYZI_FIELDS",
    "XYZ_FIELDS",
    "AdaptXModel",
    "AdaptiveMap",
    "AdaptiveMapCell",
    "AssessmentStatus",
    "BasePointCloudFrame",
    "BoundingBox3D",
    "CarlaConnectionStatus",
    "CarlaStatus",
    "ClusterRejection",
    "ComponentReadiness",
    "ComponentStatus",
    "CoordinateFrame",
    "DataSource",
    "DetectedObject",
    "DetectionConfiguration",
    "DetectionResult",
    "Dimensions",
    "ImplementationStatus",
    "LiDARSourceStatus",
    "LiDARStatus",
    "MapAccounting",
    "MapBounds",
    "MapContext",
    "MapObservation",
    "MappingConfiguration",
    "ObjectClass",
    "ObjectRisk",
    "OccupancyState",
    "PipelineConfiguration",
    "PointCloudBounds",
    "PointCloudFrame",
    "PointCloudProcessingResult",
    "PointCloudSummary",
    "PredictedTrajectory",
    "PredictionConfiguration",
    "PredictionResult",
    "PredictionStatus",
    "ProcessingMetrics",
    "ProcessingStage",
    "RawPointCloudFrame",
    "RejectedCluster",
    "ResolutionContext",
    "ResolutionDecision",
    "ResolutionLevel",
    "ResolutionSource",
    "RiskAssessment",
    "RiskAssessmentResult",
    "RiskCell",
    "RiskConfiguration",
    "RiskFactorName",
    "RiskFactors",
    "RiskField",
    "RiskLevel",
    "SkippedTrack",
    "SpatialMap",
    "SpatialMapCellField",
    "SpatialMapSummary",
    "StageMetrics",
    "SystemMetrics",
    "SystemState",
    "SystemStatus",
    "TimestampedModel",
    "TrackStatus",
    "TrackedObject",
    "TrackingConfiguration",
    "TrackingResult",
    "TrajectoryPoint",
    "TrajectoryRelevance",
    "UncertaintyBreakdown",
    "UncertaintyReason",
    "Vector3",
    "VehicleState",
    "utc_now",
]
